"""Update users' table

Revision ID: 1b1a58f316f8
Revises: e9980560c730
Create Date: 2025-03-30 16:05:00.174743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1a58f316f8'
down_revision: Union[str, None] = 'e9980560c730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'user_name',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_name',
               existing_type=sa.String(),
               nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
