"""Update tables

Revision ID: 335a53050e8f
Revises: 01357686092a
Create Date: 2025-03-07 15:21:02.065607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '335a53050e8f'
down_revision: Union[str, None] = '01357686092a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

connection_status = sa.Enum("PENDING", "EXPIRED", "ACCEPTED", "REJECTED", name="connectionstatus")
session_type = sa.Enum("SOLO", "DUO", name="sessiontype")
old_session_status = sa.Enum("ACTIVE", "EXPIRED", "COMPLETED", name="sessionstatus")
new_session_status = sa.Enum("PENDING", "ACTIVE", "AFK", "COMPLETED", name="sessionstatus")

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_requests')
    connection_status.drop(op.get_bind())

    op.drop_column('sessions', 'status')
    old_session_status.drop(op.get_bind())
    new_session_status.create(op.get_bind())  
    op.add_column('sessions', sa.Column('status', new_session_status, server_default='PENDING', nullable=False))
    
    op.add_column('sessions', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.alter_column('sessions', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('sessions_user_1_id_fkey', 'sessions', type_='foreignkey')
    op.drop_constraint('sessions_user_2_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    op.drop_column('sessions', 'session_type')
    session_type.drop(op.get_bind())
    op.drop_column('sessions', 'user_2_id')
    op.drop_column('sessions', 'user_1_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_1_id', sa.BigInteger(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('user_2_id', sa.BigInteger(), autoincrement=False, nullable=True))
    session_type.create(op.get_bind())
    op.add_column('sessions', sa.Column('session_type', session_type, server_default='SOLO', nullable=False))

    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_2_id_fkey', 'sessions', 'users', ['user_2_id'], ['id'])
    op.create_foreign_key('sessions_user_1_id_fkey', 'sessions', 'users', ['user_1_id'], ['id'])
    op.alter_column('sessions', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    op.drop_column('sessions', 'status')
    new_session_status.drop(op.get_bind())
    old_session_status.create(op.get_bind())
    op.add_column('sessions', sa.Column('status', old_session_status, server_default='ACTIVE', nullable=False))    
     
    op.drop_column('sessions', 'user_id')

    op.create_table('connection_requests',
    sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('status', connection_status, server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
