"""Update relationships

Revision ID: e9980560c730
Revises: 335a53050e8f
Create Date: 2025-03-26 21:28:05.816222

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e9980560c730'
down_revision: Union[str, None] = '335a53050e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('movie_roles_movie_id_fkey', 'movie_roles', type_='foreignkey')
    op.drop_constraint('movie_roles_person_id_fkey', 'movie_roles', type_='foreignkey')
    op.create_foreign_key('movie_roles_movie_id_fkey', 'movie_roles', 'movies', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('movie_roles_person_id_fkey', 'movie_roles', 'people', ['person_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('session_movies_movie_id_fkey', 'session_movies', type_='foreignkey')    
    op.drop_constraint('session_movies_session_user_id_fkey', 'session_movies', type_='foreignkey')
    op.create_foreign_key('session_movies_movie_id_fkey', 'session_movies', 'movies', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('session_movies_session_user_id_fkey', 'session_movies', 'sessions', ['session_id', 'user_id'], ['id', 'user_id'], ondelete='CASCADE', onupdate='CASCADE')
    
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('viewed_movies_user_id_fkey', 'viewed_movies', type_='foreignkey')
    op.drop_constraint('viewed_movies_movie_id_fkey', 'viewed_movies', type_='foreignkey')
    op.create_foreign_key('viewed_movies_user_id_fkey', 'viewed_movies', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('viewed_movies_movie_id_fkey', 'viewed_movies', 'movies', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('watch_later_movies_movie_id_fkey', 'watch_later_movies', type_='foreignkey')
    op.drop_constraint('watch_later_movies_user_id_fkey', 'watch_later_movies', type_='foreignkey')
    op.create_foreign_key('watch_later_movies_movie_id_fkey', 'watch_later_movies', 'movies', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('watch_later_movies_user_id_fkey', 'watch_later_movies', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('watch_later_movies_user_id_fkey', 'watch_later_movies', type_='foreignkey')
    op.drop_constraint('watch_later_movies_movie_id_fkey', 'watch_later_movies', type_='foreignkey')
    op.create_foreign_key('watch_later_movies_user_id_fkey', 'watch_later_movies', 'users', ['user_id'], ['id'])
    op.create_foreign_key('watch_later_movies_movie_id_fkey', 'watch_later_movies', 'movies', ['movie_id'], ['id'])
    
    op.drop_constraint('viewed_movies_movie_id_fkey', 'viewed_movies', type_='foreignkey')
    op.drop_constraint('viewed_movies_user_id_fkey', 'viewed_movies', type_='foreignkey')
    op.create_foreign_key('viewed_movies_movie_id_fkey', 'viewed_movies', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key('viewed_movies_user_id_fkey', 'viewed_movies', 'users', ['user_id'], ['id'])
    
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    
    op.drop_constraint('session_movies_session_user_id_fkey', 'session_movies', type_='foreignkey')
    op.drop_constraint('session_movies_movie_id_fkey', 'session_movies', type_='foreignkey')
    op.create_foreign_key('session_movies_session_user_id_fkey', 'session_movies', 'sessions', ['session_id', 'user_id'], ['id', 'user_id'])
    op.create_foreign_key('session_movies_movie_id_fkey', 'session_movies', 'movies', ['movie_id'], ['id'])
    
    op.drop_constraint('movie_roles_person_id_fkey', 'movie_roles', type_='foreignkey')
    op.drop_constraint('movie_roles_movie_id_fkey', 'movie_roles', type_='foreignkey')
    op.create_foreign_key('movie_roles_person_id_fkey', 'movie_roles', 'people', ['person_id'], ['id'])
    op.create_foreign_key('movie_roles_movie_id_fkey', 'movie_roles', 'movies', ['movie_id'], ['id'])
    
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
