"""Add time-columns

Revision ID: ee9aaec226fa
Revises: 51d6d927e7af
Create Date: 2025-02-24 21:06:39.647635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9aaec226fa'
down_revision: Union[str, None] = '51d6d927e7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_movies', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('viewed_movies', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('watch_later_movies', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_later_movies', 'created_at')
    op.drop_column('viewed_movies', 'created_at')
    op.drop_column('session_movies', 'created_at')
    # ### end Alembic commands ###
