services:
  nginx:
    image: nginx:alpine
    container_name: cimo_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - cimo_network

  db:
    image: postgres:17
    container_name: cimo_db
    env_file:
      - ./backend/.env.${BUILD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cimo_network

  redis:
    image: redis:7
    container_name: cimo_redis
    volumes:
      - redis_data:/data
    networks:
      - cimo_network

  backend:
    build:
      context: ./backend
    container_name: cimo_backend
    env_file:
      - ./backend/.env.${BUILD}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ["/backend/docker/app.sh", "app"]
    networks:
      - cimo_network

  celery:
    build:
      context: ./backend
    container_name: cimo_celery
    env_file:
      - ./backend/.env.${BUILD}
    depends_on:
      - redis
    command: ["/backend/docker/app.sh", "celery"]
    networks:
      - cimo_network

  flower:
    build:
      context: ./backend
    container_name: cimo_flower
    env_file:
      - ./backend/.env.${BUILD}
    ports:
      - "5555:5555"
    depends_on:
      - redis
    command: ["/backend/docker/app.sh", "flower"]
    networks:
      - cimo_network

  beat:
    build:
      context: ./backend
    container_name: cimo_beat
    env_file:
      - ./backend/.env.${BUILD}
    depends_on:
      - db
      - redis
    command: ["/backend/docker/app.sh", "beat"]
    networks:
      - cimo_network

  load-data:
    build:
      context: ./backend
    container_name: cimo_load_data
    command: ["/backend/docker/load.sh"]
    env_file:
      - ./backend/.env.${BUILD}
    depends_on:
      - db
    volumes:
      - ./backend/app/data:/app/data
    profiles:
      - manual
    networks:
      - cimo_network

  certbot:
    image: certbot/certbot
    container_name: cimo_certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email cinemood.corp@gmail.com --agree-tos --no-eff-email -d cimo-online.ru -d api.cimo-online.ru
    networks:
      - cimo_network

volumes:
  postgres_data:
  redis_data:

networks:
  cimo_network:
