"""Add 2 tables

Revision ID: 01357686092a
Revises: ee9aaec226fa
Create Date: 2025-03-05 18:30:03.212538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01357686092a'
down_revision: Union[str, None] = 'ee9aaec226fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_type = sa.Enum("ACTOR", "DIRECTOR", "BOTH", name="roletype")
movie_type = sa.Enum("MOVIE", "CARTOON", "ANIME", name="movietype")

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    movie_type.create(op.get_bind())

    op.create_table('people',
    sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_roles',
    sa.Column('movie_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.BigInteger(), nullable=False),
    sa.Column('role', role_type, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'person_id')
    )
    op.create_unique_constraint('chats_user_id_key', 'chats', ['user_id'])
    op.add_column('movies', sa.Column('type', movie_type, nullable=False))
    op.add_column('movies', sa.Column('name', sa.String(), nullable=False))
    op.add_column('movies', sa.Column('release_year', sa.BigInteger(), nullable=False))
    op.add_column('movies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('rating_kp', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('rating_imdb', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('age_rating', sa.BigInteger(), nullable=True))
    op.add_column('movies', sa.Column('poster_url', sa.String(), nullable=False))
    op.alter_column('movies', 'runtime', existing_type=sa.BigInteger(), nullable=True)
    op.drop_column('movies', 'imdb_id')
    op.drop_column('movies', 'title')
    op.drop_column('movies', 'age_restriction')
    op.drop_column('movies', 'kinopoisk_id')
    op.drop_column('movies', 'poster_id')
    op.drop_column('movies', 'overview')
    op.drop_column('movies', 'release_date')

    op.drop_constraint('viewed_movies_pkey', 'viewed_movies', type_='primary')
    op.create_primary_key('viewed_movies_pkey', 'viewed_movies', ['user_id', 'movie_id'])
    op.drop_column('viewed_movies', 'id')

    op.drop_constraint('watch_later_movies_pkey', 'watch_later_movies', type_='primary')
    op.create_primary_key('watch_later_movies_pkey', 'watch_later_movies', ['user_id', 'movie_id'])
    op.drop_column('watch_later_movies', 'id')

    op.drop_constraint('session_movies_pkey', 'session_movies', type_='primary')
    op.create_primary_key('session_movies_pkey', 'session_movies', ['session_id', 'user_id', 'movie_id'])
    op.drop_column('session_movies', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_later_movies', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('viewed_movies', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('session_movies', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))

    op.drop_constraint('session_movies_pkey', 'session_movies', type_='primary')
    op.create_primary_key('session_movies_pkey', 'session_movies', ['id'])

    op.drop_constraint('viewed_movies_pkey', 'viewed_movies', type_='primary')
    op.create_primary_key('viewed_movies_pkey', 'viewed_movies', ['id'])

    op.drop_constraint('watch_later_movies_pkey', 'watch_later_movies', type_='primary')
    op.create_primary_key('watch_later_movies_pkey', 'watch_later_movies', ['id'])

    op.add_column('movies', sa.Column('release_date', sa.Date(), autoincrement=False, nullable=False))
    op.add_column('movies', sa.Column('overview', sa.Text(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('poster_id', sa.BigInteger(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('kinopoisk_id', sa.BigInteger(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('age_restriction', sa.BigInteger(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('title', sa.String(), autoincrement=False, nullable=False))
    op.add_column('movies', sa.Column('imdb_id', sa.BigInteger(), autoincrement=False, nullable=True))
    op.alter_column('movies', 'runtime', existing_type=sa.BigInteger(), nullable=False)
    op.drop_column('movies', 'poster_url')
    op.drop_column('movies', 'age_rating')
    op.drop_column('movies', 'rating_imdb')
    op.drop_column('movies', 'rating_kp')
    op.drop_column('movies', 'description')
    op.drop_column('movies', 'release_year')
    op.drop_column('movies', 'name')
    op.drop_column('movies', 'type')
    op.drop_constraint('chats_user_id_key', 'chats', type_='unique')
    op.drop_table('movie_roles')
    op.drop_table('people')

    role_type.drop(op.get_bind())
    movie_type.drop(op.get_bind())
    # ### end Alembic commands ###
