"""Add column is_matched

Revision ID: 089697d626c0
Revises: 95d5113db80b
Create Date: 2025-04-20 16:01:34.297834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089697d626c0'
down_revision: Union[str, None] = '95d5113db80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_movies', sa.Column('is_matched', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_movies', 'is_matched')
    # ### end Alembic commands ###
