"""Update table session

Revision ID: 95d5113db80b
Revises: 1b1a58f316f8
Create Date: 2025-04-17 18:36:25.084455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '95d5113db80b'
down_revision: Union[str, None] = '1b1a58f316f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

old_session_status = sa.Enum("PENDING", "ACTIVE", "AFK", "COMPLETED", name="sessionstatus")
new_session_status = sa.Enum("PENDING", "ACTIVE", "AFK", "COMPLETED", "PREPARED", "REVIEW", name="sessionstatus")

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'status')
    old_session_status.drop(op.get_bind())
    new_session_status.create(op.get_bind())  
    op.add_column('sessions', sa.Column('status', new_session_status, server_default='PENDING', nullable=False))
    op.add_column('sessions', sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('is_pair', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('sessions', 'created_at', existing_type=sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'created_at', existing_type=sa.TIMESTAMP(timezone=True), nullable=True, server_default=None)
    op.drop_column('sessions', 'is_pair')
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'status')
    new_session_status.drop(op.get_bind())
    old_session_status.create(op.get_bind())
    op.add_column('sessions', sa.Column('status', old_session_status, server_default='PENDING', nullable=False))
    # ### end Alembic commands ###
